import type { Stage } from '@/types'

export const feb2026: Stage[] = [
  {
    id: '19-02',
    size: 9,
    grid: [
    ['red'   , 'red'   , 'red'   , 'pink'  , 'pink'  , 'blue'  , 'blue'  , 'blue'  , 'blue'  ],
    ['red'   , 'red'   , 'pink'  , 'pink'  , 'blue'  , 'blue'  , 'green' , 'blue'  , 'blue'  ],
    ['red'   , 'pink'  , 'pink'  , 'grey'  , 'blue'  , 'green' , 'green' , 'green' , 'blue'  ],
    ['pink'  , 'pink'  , 'grey'  , 'grey'  , 'grey'  , 'green' , 'green' , 'grey'  , 'blue'  ],
    ['pink'  , 'grey'  , 'grey'  , 'grey'  , 'grey'  , 'grey'  , 'grey'  , 'grey'  , 'purple'],
    ['grey'  , 'grey'  , 'yellow', 'grey'  , 'grey'  , 'grey'  , 'grey'  , 'purple', 'purple'],
    ['grey'  , 'yellow', 'yellow', 'yellow', 'grey'  , 'grey'  , 'purple', 'purple', 'brown' ],
    ['grey'  , 'yellow', 'yellow', 'grey'  , 'grey'  , 'purple', 'purple', 'orange', 'orange'],
    ['grey'  , 'grey'  , 'grey'  , 'grey'  , 'purple', 'purple', 'orange', 'orange', 'orange' ] 
  ],
},
    {
    id: '18-02',
    size: 7,
    grid: [
      ['purple', 'purple', 'purple', 'purple', 'orange', 'orange', 'blue'  ],
      ['purple', 'green' , 'green' , 'green' , 'green' , 'green' , 'blue'  ],
      ['purple', 'green' , 'grey'  , 'red'   , 'red'   , 'green' , 'blue'  ],
      ['purple', 'green' , 'grey'  , 'red'   , 'grey'  , 'green' , 'yellow'],
      ['purple', 'green' , 'grey'  , 'grey'  , 'grey'  , 'green' , 'yellow'],
      ['purple', 'green' , 'green' , 'green' , 'green' , 'green' , 'yellow'],
      ['yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow'],
    ],
  },
  {
    id: '17-02',
    size: 7,
    grid: [
      ['blue',   'blue',   'blue',   'blue',   'blue',   'red',    'red'  ],
      ['blue',   'green',  'blue',   'blue',   'red',   'red',    'grey'  ],
      ['blue',   'blue',   'blue',   'purple', 'red',    'yellow', 'grey'  ],
      ['purple', 'purple', 'purple', 'purple', 'yellow', 'yellow', 'grey'  ],
      ['purple', 'orange', 'purple', 'yellow', 'yellow', 'yellow', 'grey'  ],
      ['orange', 'orange', 'yellow', 'yellow', 'yellow', 'grey',   'grey'  ],
      ['orange', 'grey',   'grey',   'grey',   'grey',   'grey',   'grey'  ],
    ],
  },
  {
    id: '16-02',
    size: 7,
    grid: [
      ['purple', 'purple', 'purple', 'purple', 'purple', 'purple', 'purple'],
      ['orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange'],
      ['orange', 'blue'  , 'orange', 'orange', 'red'   , 'red'   , 'red'   ],
      ['blue'  , 'blue'  , 'orange', 'orange', 'red'   , 'grey'  , 'grey'  ],
      ['green' , 'blue'  , 'orange', 'orange', 'red'   , 'red'   , 'red'   ],
      ['green' , 'blue'  , 'orange', 'orange', 'red'   , 'yellow', 'red'   ],
      ['blue'  , 'blue'  , 'blue'  , 'orange', 'red'   , 'red'   , 'red'   ],
    ],
  },
  {
    id: '15-02',
    size: 9,
    grid: [
      ['red'   , 'red'   , 'red'   , 'orange', 'orange', 'orange', 'blue'  , 'blue'  , 'blue'  ],
      ['red'   , 'red'   , 'orange', 'orange', 'green' , 'orange', 'orange', 'blue'  , 'blue'  ],
      ['red'   , 'orange', 'orange', 'green' , 'green' , 'green' , 'orange', 'orange', 'blue'  ],
      ['orange', 'orange', 'grey'  , 'grey'  , 'grey'  , 'green' , 'purple', 'orange', 'orange'],
      ['orange', 'grey'  , 'grey'  , 'grey'  , 'green' , 'green' , 'purple', 'purple', 'orange'],
      ['orange', 'orange', 'grey'  , 'grey'  , 'grey'  , 'grey'  , 'purple', 'orange', 'orange'],
      ['yellow', 'orange', 'orange', 'grey'  , 'grey'  , 'grey'  , 'orange', 'orange', 'brown' ],
      ['yellow', 'yellow', 'orange', 'orange', 'grey'  , 'orange', 'orange', 'brown' , 'brown' ],
      ['pink'  , 'pink'  , 'pink'  , 'orange', 'orange', 'orange', 'brown' , 'brown' , 'brown' ],
    ],
  },
  {
    id: '14-02',
    size: 9,
    grid: [
      ['purple', 'purple', 'purple', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow'],
      ['pink'  , 'pink'  , 'purple', 'pink'  , 'pink'  , 'brown' , 'yellow', 'yellow', 'yellow'],
      ['pink'  , 'pink'  , 'pink'  , 'pink'  , 'pink'  , 'brown' , 'yellow', 'yellow', 'yellow'],
      ['grey'  , 'pink'  , 'pink'  , 'pink'  , 'brown' , 'brown' , 'yellow', 'yellow', 'yellow'],
      ['grey'  , 'grey'  , 'pink'  , 'grey'  , 'brown' , 'yellow', 'yellow', 'yellow', 'yellow'],
      ['blue'  , 'grey'  , 'grey'  , 'grey'  , 'red'   , 'red'   , 'yellow', 'red'   , 'red'   ],
      ['blue'  , 'blue'  , 'blue'  , 'grey'  , 'red'   , 'red'   , 'red'   , 'red'   , 'red'   ],
      ['green' , 'blue'  , 'blue'  , 'grey'  , 'grey'  , 'red'   , 'red'   , 'red'   , 'orange'],
      ['green' , 'green' , 'blue'  , 'blue'  , 'grey'  , 'grey'  , 'red'   , 'orange', 'orange'],
    ],
  },
  {
    id: '13-02',
    size: 8,
    grid: [
      ['purple', 'purple', 'purple', 'orange', 'orange', 'orange', 'orange', 'orange'],
      ['purple', 'purple', 'purple', 'orange', 'blue'  , 'blue'  , 'green' , 'green' ],
      ['purple', 'purple', 'purple', 'purple', 'purple', 'blue'  , 'green' , 'green' ],
      ['grey'  , 'grey'  , 'purple', 'purple', 'purple', 'purple', 'green' , 'green' ],
      ['red'   , 'grey'  , 'purple', 'purple', 'purple', 'purple', 'green' , 'green' ],
      ['red'   , 'grey'  , 'grey'  , 'purple', 'purple', 'purple', 'purple', 'purple'],
      ['red'   , 'yellow', 'yellow', 'yellow', 'brown' , 'purple', 'purple', 'purple'],
      ['red'   , 'red'   , 'red'   , 'yellow', 'brown' , 'purple', 'purple', 'purple'],
    ],
  },
  {
    id: '12-02',
    size: 9,
    grid: [
      ['purple', 'purple', 'orange', 'orange', 'orange', 'orange', 'orange', 'blue'  , 'blue'  ],
      ['purple', 'orange', 'orange', 'red'   , 'red'   , 'red'   , 'orange', 'orange', 'blue'  ],
      ['purple', 'orange', 'red'   , 'red'   , 'red'   , 'red'   , 'red'   , 'orange', 'grey'  ],
      ['purple', 'orange', 'orange', 'red'   , 'red'   , 'red'   , 'orange', 'orange', 'grey'  ],
      ['purple', 'purple', 'orange', 'orange', 'red'   , 'orange', 'orange', 'grey'  , 'grey'  ],
      ['green' , 'purple', 'purple', 'orange', 'orange', 'orange', 'grey'  , 'grey'  , 'grey'  ],
      ['green' , 'green' , 'green' , 'green' , 'yellow', 'grey'  , 'grey'  , 'grey'  , 'grey'  ],
      ['green' , 'green' , 'brown' , 'brown' , 'yellow', 'pink'  , 'pink'  , 'grey'  , 'grey'  ],
      ['green' , 'brown' , 'brown' , 'brown' , 'yellow', 'pink'  , 'pink'  , 'pink'  , 'grey'  ],
    ],
  },

]
